/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91__reviewChar93RouteImport } from './routes/[__review]'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91__reviewChar93IndexRouteImport } from './routes/[__review].index'
import { Route as Char91__reviewChar93ColaboradoresRouteImport } from './routes/[__review].colaboradores'
import { Route as Char91__reviewChar93ComprasRouteImport } from './routes/[__review].compras'
import { Route as Char91__reviewChar93ConsumoRouteImport } from './routes/[__review].consumo'
import { Route as Char91__reviewChar93EntregasRouteImport } from './routes/[__review].entregas'
import { Route as Char91__reviewChar93EpisRouteImport } from './routes/[__review].epis'
import { Route as Char91__reviewChar93InventarioRouteImport } from './routes/[__review].inventario'
import { Route as Char91__reviewChar93RelatoriosRouteImport } from './routes/[__review].relatorios'
import { Route as AppColaboradoresRouteImport } from './routes/_app/colaboradores'
import { Route as AppComprasRouteImport } from './routes/_app/compras'
import { Route as AppConsumoRouteImport } from './routes/_app/consumo'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppEntregasRouteImport } from './routes/_app/entregas'
import { Route as AppEpisRouteImport } from './routes/_app/epis'
import { Route as AppInventarioRouteImport } from './routes/_app/inventario'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AppColaboradoresIdRouteImport } from './routes/_app/colaboradores_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91__reviewChar93Route = Char91__reviewChar93RouteImport.update({
  id: '/__review',
  path: '/__review',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__reviewChar93IndexRoute =
  Char91__reviewChar93IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char91__reviewChar93Route,
  } as any)
const Char91__reviewChar93ColaboradoresRoute =
  Char91__reviewChar93ColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => Char91__reviewChar93Route,
  } as any)
const Char91__reviewChar93ComprasRoute =
  Char91__reviewChar93ComprasRouteImport.update({
    id: '/compras',
    path: '/compras',
    getParentRoute: () => Char91__reviewChar93Route,
  } as any)
const Char91__reviewChar93ConsumoRoute =
  Char91__reviewChar93ConsumoRouteImport.update({
    id: '/consumo',
    path: '/consumo',
    getParentRoute: () => Char91__reviewChar93Route,
  } as any)
const Char91__reviewChar93EntregasRoute =
  Char91__reviewChar93EntregasRouteImport.update({
    id: '/entregas',
    path: '/entregas',
    getParentRoute: () => Char91__reviewChar93Route,
  } as any)
const Char91__reviewChar93EpisRoute =
  Char91__reviewChar93EpisRouteImport.update({
    id: '/epis',
    path: '/epis',
    getParentRoute: () => Char91__reviewChar93Route,
  } as any)
const Char91__reviewChar93InventarioRoute =
  Char91__reviewChar93InventarioRouteImport.update({
    id: '/inventario',
    path: '/inventario',
    getParentRoute: () => Char91__reviewChar93Route,
  } as any)
const Char91__reviewChar93RelatoriosRoute =
  Char91__reviewChar93RelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => Char91__reviewChar93Route,
  } as any)
const AppColaboradoresRoute = AppColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => AppRoute,
} as any)
const AppComprasRoute = AppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppRoute,
} as any)
const AppConsumoRoute = AppConsumoRouteImport.update({
  id: '/consumo',
  path: '/consumo',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEntregasRoute = AppEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AppRoute,
} as any)
const AppEpisRoute = AppEpisRouteImport.update({
  id: '/epis',
  path: '/epis',
  getParentRoute: () => AppRoute,
} as any)
const AppInventarioRoute = AppInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppColaboradoresIdRoute = AppColaboradoresIdRouteImport.update({
  id: '/colaboradores_/$id',
  path: '/colaboradores/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/__review': typeof Char91__reviewChar93RouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/__review/colaboradores': typeof Char91__reviewChar93ColaboradoresRoute
  '/__review/compras': typeof Char91__reviewChar93ComprasRoute
  '/__review/consumo': typeof Char91__reviewChar93ConsumoRoute
  '/__review/entregas': typeof Char91__reviewChar93EntregasRoute
  '/__review/epis': typeof Char91__reviewChar93EpisRoute
  '/__review/inventario': typeof Char91__reviewChar93InventarioRoute
  '/__review/relatorios': typeof Char91__reviewChar93RelatoriosRoute
  '/colaboradores': typeof AppColaboradoresRoute
  '/compras': typeof AppComprasRoute
  '/consumo': typeof AppConsumoRoute
  '/dashboard': typeof AppDashboardRoute
  '/entregas': typeof AppEntregasRoute
  '/epis': typeof AppEpisRoute
  '/inventario': typeof AppInventarioRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/__review/': typeof Char91__reviewChar93IndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/colaboradores/$id': typeof AppColaboradoresIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/__review/colaboradores': typeof Char91__reviewChar93ColaboradoresRoute
  '/__review/compras': typeof Char91__reviewChar93ComprasRoute
  '/__review/consumo': typeof Char91__reviewChar93ConsumoRoute
  '/__review/entregas': typeof Char91__reviewChar93EntregasRoute
  '/__review/epis': typeof Char91__reviewChar93EpisRoute
  '/__review/inventario': typeof Char91__reviewChar93InventarioRoute
  '/__review/relatorios': typeof Char91__reviewChar93RelatoriosRoute
  '/colaboradores': typeof AppColaboradoresRoute
  '/compras': typeof AppComprasRoute
  '/consumo': typeof AppConsumoRoute
  '/dashboard': typeof AppDashboardRoute
  '/entregas': typeof AppEntregasRoute
  '/epis': typeof AppEpisRoute
  '/inventario': typeof AppInventarioRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/__review': typeof Char91__reviewChar93IndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/colaboradores/$id': typeof AppColaboradoresIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__review': typeof Char91__reviewChar93RouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/__review/colaboradores': typeof Char91__reviewChar93ColaboradoresRoute
  '/__review/compras': typeof Char91__reviewChar93ComprasRoute
  '/__review/consumo': typeof Char91__reviewChar93ConsumoRoute
  '/__review/entregas': typeof Char91__reviewChar93EntregasRoute
  '/__review/epis': typeof Char91__reviewChar93EpisRoute
  '/__review/inventario': typeof Char91__reviewChar93InventarioRoute
  '/__review/relatorios': typeof Char91__reviewChar93RelatoriosRoute
  '/_app/colaboradores': typeof AppColaboradoresRoute
  '/_app/compras': typeof AppComprasRoute
  '/_app/consumo': typeof AppConsumoRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/entregas': typeof AppEntregasRoute
  '/_app/epis': typeof AppEpisRoute
  '/_app/inventario': typeof AppInventarioRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/__review/': typeof Char91__reviewChar93IndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_app/colaboradores_/$id': typeof AppColaboradoresIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/__review'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/__review/colaboradores'
    | '/__review/compras'
    | '/__review/consumo'
    | '/__review/entregas'
    | '/__review/epis'
    | '/__review/inventario'
    | '/__review/relatorios'
    | '/colaboradores'
    | '/compras'
    | '/consumo'
    | '/dashboard'
    | '/entregas'
    | '/epis'
    | '/inventario'
    | '/relatorios'
    | '/usuarios'
    | '/__review/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/colaboradores/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/__review/colaboradores'
    | '/__review/compras'
    | '/__review/consumo'
    | '/__review/entregas'
    | '/__review/epis'
    | '/__review/inventario'
    | '/__review/relatorios'
    | '/colaboradores'
    | '/compras'
    | '/consumo'
    | '/dashboard'
    | '/entregas'
    | '/epis'
    | '/inventario'
    | '/relatorios'
    | '/usuarios'
    | '/__review'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/colaboradores/$id'
  id:
    | '__root__'
    | '/'
    | '/__review'
    | '/_app'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/__review/colaboradores'
    | '/__review/compras'
    | '/__review/consumo'
    | '/__review/entregas'
    | '/__review/epis'
    | '/__review/inventario'
    | '/__review/relatorios'
    | '/_app/colaboradores'
    | '/_app/compras'
    | '/_app/consumo'
    | '/_app/dashboard'
    | '/_app/entregas'
    | '/_app/epis'
    | '/_app/inventario'
    | '/_app/relatorios'
    | '/_app/usuarios'
    | '/__review/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_app/colaboradores_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char91__reviewChar93Route: typeof Char91__reviewChar93RouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__review': {
      id: '/__review'
      path: '/__review'
      fullPath: '/__review'
      preLoaderRoute: typeof Char91__reviewChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__review/': {
      id: '/__review/'
      path: '/'
      fullPath: '/__review/'
      preLoaderRoute: typeof Char91__reviewChar93IndexRouteImport
      parentRoute: typeof Char91__reviewChar93Route
    }
    '/__review/colaboradores': {
      id: '/__review/colaboradores'
      path: '/colaboradores'
      fullPath: '/__review/colaboradores'
      preLoaderRoute: typeof Char91__reviewChar93ColaboradoresRouteImport
      parentRoute: typeof Char91__reviewChar93Route
    }
    '/__review/compras': {
      id: '/__review/compras'
      path: '/compras'
      fullPath: '/__review/compras'
      preLoaderRoute: typeof Char91__reviewChar93ComprasRouteImport
      parentRoute: typeof Char91__reviewChar93Route
    }
    '/__review/consumo': {
      id: '/__review/consumo'
      path: '/consumo'
      fullPath: '/__review/consumo'
      preLoaderRoute: typeof Char91__reviewChar93ConsumoRouteImport
      parentRoute: typeof Char91__reviewChar93Route
    }
    '/__review/entregas': {
      id: '/__review/entregas'
      path: '/entregas'
      fullPath: '/__review/entregas'
      preLoaderRoute: typeof Char91__reviewChar93EntregasRouteImport
      parentRoute: typeof Char91__reviewChar93Route
    }
    '/__review/epis': {
      id: '/__review/epis'
      path: '/epis'
      fullPath: '/__review/epis'
      preLoaderRoute: typeof Char91__reviewChar93EpisRouteImport
      parentRoute: typeof Char91__reviewChar93Route
    }
    '/__review/inventario': {
      id: '/__review/inventario'
      path: '/inventario'
      fullPath: '/__review/inventario'
      preLoaderRoute: typeof Char91__reviewChar93InventarioRouteImport
      parentRoute: typeof Char91__reviewChar93Route
    }
    '/__review/relatorios': {
      id: '/__review/relatorios'
      path: '/relatorios'
      fullPath: '/__review/relatorios'
      preLoaderRoute: typeof Char91__reviewChar93RelatoriosRouteImport
      parentRoute: typeof Char91__reviewChar93Route
    }
    '/_app/colaboradores': {
      id: '/_app/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AppColaboradoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compras': {
      id: '/_app/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AppComprasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consumo': {
      id: '/_app/consumo'
      path: '/consumo'
      fullPath: '/consumo'
      preLoaderRoute: typeof AppConsumoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entregas': {
      id: '/_app/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AppEntregasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/epis': {
      id: '/_app/epis'
      path: '/epis'
      fullPath: '/epis'
      preLoaderRoute: typeof AppEpisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventario': {
      id: '/_app/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AppInventarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/colaboradores_/$id': {
      id: '/_app/colaboradores_/$id'
      path: '/colaboradores/$id'
      fullPath: '/colaboradores/$id'
      preLoaderRoute: typeof AppColaboradoresIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface Char91__reviewChar93RouteChildren {
  Char91__reviewChar93ColaboradoresRoute: typeof Char91__reviewChar93ColaboradoresRoute
  Char91__reviewChar93ComprasRoute: typeof Char91__reviewChar93ComprasRoute
  Char91__reviewChar93ConsumoRoute: typeof Char91__reviewChar93ConsumoRoute
  Char91__reviewChar93EntregasRoute: typeof Char91__reviewChar93EntregasRoute
  Char91__reviewChar93EpisRoute: typeof Char91__reviewChar93EpisRoute
  Char91__reviewChar93InventarioRoute: typeof Char91__reviewChar93InventarioRoute
  Char91__reviewChar93RelatoriosRoute: typeof Char91__reviewChar93RelatoriosRoute
  Char91__reviewChar93IndexRoute: typeof Char91__reviewChar93IndexRoute
}

const Char91__reviewChar93RouteChildren: Char91__reviewChar93RouteChildren = {
  Char91__reviewChar93ColaboradoresRoute:
    Char91__reviewChar93ColaboradoresRoute,
  Char91__reviewChar93ComprasRoute: Char91__reviewChar93ComprasRoute,
  Char91__reviewChar93ConsumoRoute: Char91__reviewChar93ConsumoRoute,
  Char91__reviewChar93EntregasRoute: Char91__reviewChar93EntregasRoute,
  Char91__reviewChar93EpisRoute: Char91__reviewChar93EpisRoute,
  Char91__reviewChar93InventarioRoute: Char91__reviewChar93InventarioRoute,
  Char91__reviewChar93RelatoriosRoute: Char91__reviewChar93RelatoriosRoute,
  Char91__reviewChar93IndexRoute: Char91__reviewChar93IndexRoute,
}

const Char91__reviewChar93RouteWithChildren =
  Char91__reviewChar93Route._addFileChildren(Char91__reviewChar93RouteChildren)

interface AppRouteChildren {
  AppColaboradoresRoute: typeof AppColaboradoresRoute
  AppComprasRoute: typeof AppComprasRoute
  AppConsumoRoute: typeof AppConsumoRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEntregasRoute: typeof AppEntregasRoute
  AppEpisRoute: typeof AppEpisRoute
  AppInventarioRoute: typeof AppInventarioRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppColaboradoresIdRoute: typeof AppColaboradoresIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppColaboradoresRoute: AppColaboradoresRoute,
  AppComprasRoute: AppComprasRoute,
  AppConsumoRoute: AppConsumoRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEntregasRoute: AppEntregasRoute,
  AppEpisRoute: AppEpisRoute,
  AppInventarioRoute: AppInventarioRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppColaboradoresIdRoute: AppColaboradoresIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char91__reviewChar93Route: Char91__reviewChar93RouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
